### ISSUE TITLE
DataTables View won't load data when embedded in a Single Entry List View

### ISSUE THREAD

**Issue by crbdev** [GravityKit/GravityView#2090] opened 2024-07-29 05:25 UTC
When adding a DataTables View (using the "GravityView - View" field in the view editor) to a Single Entry page using the List layout, the DataTables View does not load any data.

- Create two new Views: a list View and a DataTables view and add some entries
- Using the "GravityView - Vew" field, embed the DataTables View into the list View's Single Entry page (add the field to the "Other Fields" section)
- View it on the front-end
- Confirm you cannot see entries from the embedded DataTables View
- Drag and drop the "GravityView - View" field to a different section in the View editor
- Confirm you can now see data from the embedded DataTables View

Example:
https://flamboyant-swiftlet-eb7a39.try.gravitykit.com/view/business-database/entry/1214/ 

WordPress 6.6.1 
PHP version is: 7.4.33

**Comment by mrcasual** [comment] 2024-08-08 23:46
@omarkasem, please work on this.

**Comment by omarkasem** [comment] 2024-09-19 07:08
@crbdev @mrcasual 
I tested that multiple times and it's working fine for me
php 7.4 and 8.1
gv 2.28.0
datatables 3.3.7

**Comment by crbdev** [comment] 2024-09-20 03:11
I've tested it on try. and my local install, and it doesn't work. @Mwalek could you please try to reproduce this? Let me know if the steps aren't clear.

![CleanShot 2024-09-20 at 11 10 30@2x](https://github.com/user-attachments/assets/8c8bcbee-b104-4cb1-a3d0-0599fcef80b0)

**Comment by Mwalek** [comment] 2024-09-20 22:42
@crbdev I tested with PHP 7.4 and 8.3, but couldn't reproduce.

Perhaps you could have a look at my test and make adjustments or provide further clarification:

https://basecamp.try.gravitykit.com/view/issue-2090-view/

**Comment by Mwalek** [comment] 2024-09-23 04:23
@crbdev here you go, **u**: admin1 **p**: test

**Comment by crbdev** [comment] 2024-09-23 04:32
@Mwalek @omarkasem Thanks! Okay, so the issue only occurs when adding the field to the "Other Fields" section of the View editor

![CleanShot 2024-09-23 at 12 31 41@2x](https://github.com/user-attachments/assets/04005baa-0f3b-4aa1-b67c-2eab8dd26ccd)

![CleanShot 2024-09-23 at 12 31 10@2x](https://github.com/user-attachments/assets/7d2045f4-8654-48a3-b638-dc569da37cfe)

**Comment by omarkasem** [comment] 2024-09-23 18:37
Thanks @crbdev for clarifying that.
It's fixed now with this PR https://github.com/GravityKit/GravityView/pull/2149

**Closed** 2024-09-24 21:09 UTC
Labels: Bug
