### ISSUE TITLE
Plugin Updater Conflict with ManageWP Orion

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#896] opened 2017-06-02 17:21 UTC
> We use [ManageWP Orion](http://orion.managewp.com) to update plugins. None of the plugins on our site (kids-harbor.com) show they need updating (even though many have updates available).
> 
> Through a process of elimination, we were able to trace this back to the GravityView plugin. With this plugin temporarily deactivated, we were able to see and apply a number of available updates that were being hidden previously. We also applied available updates for the GravityView plugin; however, the issue seems to still be present (the available update for the Akismet plugin is not showing in the admin dashboard nor in Manage WP Orion).

https://secure.helpscout.net/conversation/374668355/9479/?folderId=408730

See easydigitaldownloads/EDD-Software-Licensing#1094

![screen-shot-2017-06-02-at-10 01 28-am](https://cloud.githubusercontent.com/assets/870979/26737002/9b30f0e2-4785-11e7-96ca-c06cf9f305e1.png)
![screen-shot-2017-06-02-at-10 03 10-am](https://cloud.githubusercontent.com/assets/870979/26737001/9b2e0fa8-4785-11e7-80b6-530f6cbbc62e.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/995529792029955/995655080291217)

**Comment by zackkatz** [comment] 2017-06-02 17:26
Contacted ManageWP; waiting to hear back.

**Comment by jakejackson1** [comment] 2017-07-05 23:08
This may be related...

I've been tracking down a slow admin area issue. Turns out it was because the plugin updater was running on each page in the admin area. Process of elimination pointed the cause at GravityView. Upon deactivation, the update transient was successfully saved and the updater was no longer running each admin page load. Re-activating GravityView caused no further problems until the transient expired, in which case the problem re-occured.

This is on a site running GravityView 1.21.3.

**Comment by zackkatz** [comment] 2017-11-28 06:08
b851221 fixed it!

**Comment by zackkatz** [comment] 2018-01-10 01:29
No, b851221 didn't fix it…

**Comment by rafaehlers** [comment] 2021-10-04 22:32
Closing since no one reported this anymore.

**Comment by rafaehlers** [comment] 2024-02-02 17:28
It's happening again: https://support.gravitykit.com/conversation/76479

>Got a different question though, I use ManageWP to handle most updates and such, and I've been noticing that since you merged/got Foundation the plugin updates don't show there. Is there a way to avoid that? Nothing huge/important, just a QoL thing for me, since this site is a bit complex, I manage most of the updates and such manually though. But I get the heads up from there.

**Comment by floatytheastronaut** [comment] 2024-02-02 17:29
FreeScout #76479. <br>https://support.gravitykit.com/conversation/76479?folder_id=1

**Comment by rafaehlers** [comment] 2024-02-02 18:33
@mrcasual checked and it's working as expected: https://www.loom.com/share/232bfc70559e4e3694c0d474e990ee30

**Closed by rafaehlers** 2024-02-02 18:33 UTC
Labels: Bug, Core: Administration, Compat: Multisite
