### ISSUE TITLE
Bulk approval issue with the "Select all X entries" link

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#1840] opened 2023-04-12 00:35 UTC
The link to `Select all X entries.`  affects all entries in the form, ignoring the filter we are currently in:

![image](https://user-images.githubusercontent.com/1222472/231317555-91278da3-0767-4e41-8320-792f3f8b0063.png)

Here's how to reproduce:

![image](https://user-images.githubusercontent.com/1222472/231317358-89f4448b-910f-4e4a-a802-fa6247c292e6.png)

Tested on GV 2.17.4

**Comment by rafaehlers** [comment] 2023-04-12 00:38
https://secure.helpscout.net/conversation/2210748574/48210/

**Comment by zackkatz** [comment] 2023-04-27 20:50
This was a duplicate of #1799

**Closed** 2023-04-27 20:49 UTC
Labels: Bug
