### ISSUE TITLE
By default, "Show Labels" is unchecked when adding a field in the Edit view of Listing Layout

### ISSUE THREAD

**Issue by tobifjellner** [GravityKit/GravityView#2021] opened 2024-03-28 09:19 UTC
**Describe the Issue**
In "List" layout type, when adding a field in the Edit Entry layout, the option "Show Labels" is by default "Off".

I confirmed this on "Try" March 28, 2024, with GV 2.19.6

**Replication Steps:**

- Navigate to the Views list: /wp-admin/admin.php?page=gravityview_all_views.
- Select an existing view to edit or create a new one.
- Go to the "Edit Entry Layout" tab.
- Add a field under "Visible Edit Fields."
- Click the configure (cogwheel) icon next to the added field.
- Observe the state of the "Show Label" checkbox.

**Expected Behavior:** The "Show Label" checkbox should be checked by default.

**Actual Behavior:** The "Show Label" checkbox is unchecked by default.

**Comment by floatytheastronaut** [comment] 2024-03-28 09:20
FreeScout #78528. <br>https://support.gravitykit.com/conversation/78528?folder_id=1

**Comment by mrcasual** [comment] 2024-08-08 23:50
@Mwalek, please reproduce, update the issue description with clear instructions/steps, and see if you can fix this.

**Comment by Mwalek** [comment] 2024-08-09 09:58
I have successfully reproduced the issue and am in the process of resolving it. I am close to a solution and will share the updated branch once the changes have been pushed.

**Comment by Mwalek** [comment] 2024-08-09 19:54
I couldn't reproduce this issue on other WordPress installations; it appears to be resolved. I tested multiple releases, including the latest develop version, and the issue no longer occurs. @rafaehlers, could you please inform the relevant users that the issue has been fixed?

**Comment by rafaehlers** [comment] 2024-08-09 20:04
No need to notify the user in this case. Closing! Thanks for checking @Mwalek 🙏

**Closed by rafaehlers** 2024-08-09 20:04 UTC
